//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LLCComputers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public int ManufacturerId { get; set; }
        public int ProductGroupId { get; set; }
        public int Price { get; set; }
        public int Discount { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
    }
}
